- file:
    path: $HOME/.bash.d
    state: directory
    mode: 0755
- ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: $HOME/.asdf
    version: v0.10.0
- file:
    path: $HOME/.bash.d/asdf.sh
    mode: 0644
